### ISSUE TITLE
No Front End Message shown for reaching Quota in Modifier (Neither Explorer nor for Professional) 

### ISSUE THREAD

**Issue by Aadjou** [archilogic-com/3dio-modify-app#7]
Moved from https://github.com/archilogic-com/services/issues/325

Actual:
Reached quota as Explorer and Professional and did not get any message, the modifier just stopped modifying.
There is a message in the inspect console.

Expected:
Get a message pop up that tells me I reached my quota instead of having to find out in the console as it is a ready to use App.

See issue 
<img width="1440" alt="screen shot 2017-09-12 at 16 24 16" src="https://user-images.githubusercontent.com/30081479/30331240-8981dbac-97d7-11e7-83cb-7b420e851642.png">
#316

**Comment by mope1** [comment]
https://github.com/archilogic-com/3dio-modify-app/pull/9
